### ISSUE TITLE
question about flannel

### ISSUE THREAD

**Issue by HamzaZo** [zlbabe/Kubernetes-the-hard-way-with-Ansible#1]
Hello
I have a question about the flannel role , at any time you apply this role ? and flannel you install it on the worker node or on the master node ?

Thank you for your reply

**Comment by zlbabe** [comment]
| at any time you apply this role ?

Flannel is a made as dependency of `docker` role :
```
$ cat roles/docker/meta/main.yml 
---
dependencies:
  - { role: flannel }
```
and docker role is called by `k8s-worker` role in `roles/k8s-worker/tasks/main.yml` file
```
- name: Include docker role
  include_role:
    name: docker
```

Flannel is installed only on worker nodes.
