### ISSUE TITLE
ansible: Create /var/lib/etcd directory failed

### ISSUE THREAD

**Issue by bartos** [zlbabe/Kubernetes-the-hard-way-with-Ansible#2]
Hello,

I think you should reorder tasks and put `Create etcd user` before `name: Create etcd user` in [etcd playbook](https://github.com/zlbabe/Kubernetes-the-hard-way-with-Ansible/blob/master/roles/etcd/tasks/main.yml). It fails for all three masters in default configuration with fresh VMs.

Great job any way!
Regards,
B.

**Comment by zlbabe** [comment]
Thanks @bartos for reporting this issue. 
it will be fixed today ;)

**Comment by zlbabe** [comment]
Fixed.
