### ISSUE TITLE
Nginx SSL Support issue

### ISSUE THREAD

**Issue by pradeepjaladi** [zlbabe/Kubernetes-the-hard-way-with-Ansible#3]
Hi,

I am trying to setup the kubernetes cluster info using the repo. Before i ran the ansible play book, Was not the nginx shouold be running on https port instead of http. I say the kube script is setting https://<<loadbalance>:6443 port. Please let me know if this repo will work as is on rhel ( I will change the apt to yum tasks )

**Comment by zlbabe** [comment]
Hi,
nginx is setup as **TCP load balancer** (https://docs.nginx.com/nginx/admin-guide/load-balancer/tcp-udp-load-balancer/).
for the second question, I didn't try on rhel, I always work on Debian/ubuntu distros.

**Comment by pradeepjaladi** [comment]
But nginx is available on http on ports ( 80, 6443, 2379 ) not on https, in configuration of kubectl we are configuring https and i am getting server related internal error when i run kubectl apply rbac

**Comment by zlbabe** [comment]
the port 80 is not used, and kubectl configuration file is setup to use 6443 and 2379 ports. (look at scripts/kubectl_conf.sh).

The error with RBAC is related to the fact that the master may not be ready at the moment where the configuration is pushed. The workaround that I put in place is to retry 3 times max ( look at the task `Configure RBAC for kubelet authorization` in `roles/k8s-master/tasks/main.yml`.

If you still have problems with kubectl, verify that kubectl is using the right context.
