### ISSUE TITLE
Dashboard Pod not starting

### ISSUE THREAD

**Issue by pradeepjaladi** [zlbabe/Kubernetes-the-hard-way-with-Ansible#4]
Hi,

I customized the repo to support RHEL & openssl and able to successfully deploy master  and nodes with out load balancer. When i ran addon the coreDNS was deploying but the Dashboard was going into CrasshLoopBackOff. Where you able to successfully deploy the Dashboard ? or is there any custom configuration related to Ubuntu and coreOS

**Comment by zlbabe** [comment]
Sorry but I can't help as it's not related to this repo. If you make your own customization it's up to you to debug when it goes wrong.
